name: Release macos bundle

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - run: mkdir ~/gtk
    - run: echo "Hello World!" > ~/gtk/hello

    - run: tar -czf ./gtk.tar.xz ~/gtk

    - uses: actions/upload-artifact@v1
      with:
        name: gtk.tar.xz
        path: ./gtk.tar.xz
