name: Release macos bundle

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - run: brew install gtk+3
    - run: brew info --json=v1 gtk+3
    - run: ./grab.py

    - uses: actions/upload-artifact@v1
      with:
        name: gtk.tar
        path: ./gtk.tar
