name: Release macos bundle

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Bump pipenv
      run: brew install gtk+3

    - run: tar -czf ./gtk.tar.xz /usr/local/opt

    - uses: actions/upload-artifact@v1
      with:
        name: gtk.tar.xz
        path: ./gtk.tar.xz
